### ISSUE TITLE
[BUG] Export of external documents (possibly more) does not respect "include unpublished"

### ISSUE THREAD

**Issue by lorawoodford** [Smithsonian/lassb-ead-exporter#10]
**Describe the bug**
When exporting EAD2002 for a resource/archival object containing at least one unpublished external document, that external document is NOT exported in the EAD even when I select "include unpublished?" during my export.

**To Reproduce**
1. Go to a resource/archival object containing an unpublished external document (in test, I've added an unpublished external document to: https://aspacetest.si.edu/resources/53849)
2. Click on "Export" > "Download EAD" and check "Include unpublished"
3. After exporting your EAD, open the resulting file.
4. Search the file for your external document note
5. The note is not there, even though we've requested unpublished items in our export

**Expected behavior**
My external document should be exported since I've requested my export to include unpublished content.  Similarly, the current code suggests this was intended behavior for both resource records (https://github.com/Smithsonian/lassb-ead-exporter/blob/main/backend/lib/si_ead_extras_serialize.rb#L22) and archival objects (https://github.com/Smithsonian/lassb-ead-exporter/blob/main/backend/lib/si_ead_extras_serialize.rb#L7).

**Screenshots**

_Optional, but include if helpful/relevant_
**Desktop:**

**Smartphone/Mobile:**

**Additional context**

**Comment by fordmadox** [comment]
Yeah, I'm quite certain that this was skipped originally (and intentionally) due to the only use case for those external documents being for display only (not migration, etc.) -- and I'm pretty sure that's a safe assumption, although I just posted the code to GH (didn't write it). That said, our local extensions should follow the conventions of using audience='internal' if unpublished data points are requested, so yes, please do add this feature!!!
